user_name = input("What is your name?")
user_age = input("How old are you?")
user_location = input("Where do you live?")
print("Hello,", user_name)
print("Your age is", user_age )
print("You live in", user_location)