name=input("What is your name?")
city=input("Where do you live?")
age = input("How old are you")
age = int(age)
print("Hello,", name.title())
print("Your age is",age)
print("You live in",city.title())